"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    hero_title: "The Help Desk for the Kingdom.",
    hero_subtitle: "Navigating Saudi Arabia's labor market and government services, simplified through community knowledge and AI.",
    hero_ai_desc: "Ask our AI assistant to help and support.",
    ask_ai_placeholder: "Ask AI: How to calculate End of Service Benefit?",
    ask_expert: "Ask Expert",
    labor_law: "Labor Law",
    contract_rules: "Contract Rules",
    worker_rights: "Worker Rights",
    search_placeholder: "Search: Visa, Salary, Contract, Iqama...",
    public_qa: "Public Q&A",
    official_links: "Official Links",
    essential_apps: "Essential Apps",
    ask_question: "Ask Question",
    latest_news: "Latest News",
    nav_home: "Home",
    nav_labor_tools: "Labor & Tools",
    nav_labor_office: "Labor Office Guide",
    nav_eosb: "EOSB Calculator",
    nav_tools: "Utility Tools",
    nav_guide: "Guide",
    nav_resources: "Resources",
    nav_jobs: "Jobs",
    nav_about: "About",
    nav_news: "News",
    footer_mission: "Empowering the workforce with clear knowledge, official updates, and a supportive community for all expats and citizens.",
    footer_disclaimer: "Disclaimer: This is a community-driven initiative and is not an official government entity. Always verify critical information directly with MHRSD or relevant official channels.",
    ask_community: "Ask the Community",
    need_help: "Need Help?",
    ask_community_desc: "Can’t find the answer in our Knowledge Base? Submit your specific labor or visa-related question below. Our support team will review your request and respond to you via email or phone with the provided contact details.",
    your_question: "Your Question",
    question_placeholder: "E.g., How do I calculate my end of service benefit after 3 years?",
    email_address: "Email Address",
    mobile_number: "Mobile Number",
    submit_question: "Submit Question",
    processing: "Processing...",
    question_submitted: "Question Submitted",
    question_received_desc: "We've received your question. You will receive an email notification once an official response is posted.",
    ask_another_question: "Ask Another Question",
    kb_knowledge_base: "Knowledge Base",
    kb_public_qa: "Public Q&A Directory",
    kb_filter_placeholder: "Filter by keyword...",
    kb_no_results: "No results found for",
    kb_clear_filters: "Clear filters",
    kb_official_guidance: "Official Guidance",
    general: "General",
    file_report: "File a Report",
    report_desc: "Submit your grievances directly through our secure portal. All submissions are treated with strict confidentiality and routed for official review.",
    encrypted: "End-to-End Encrypted",
    immediate_routing: "Immediate Case Routing",
    mobile_verification: "Mobile Verification",
    report_submitted: "Report Submitted",
    report_logged_desc: "Your report has been logged securely. Our team will contact you shortly on the provided mobile number.",
    submit_another_report: "Submit Another Report",
    report_details: "Report Details",
    describe_issue: "Describe the issue clearly...",
    important_bulletins: "Important Bulletins",
    labor_alerts: "Official Labor Alerts",
    view_all_updates: "View All Updates",
    read_details: "Read Details",
    ai_labor_insights: "AI Labor Insights",
    automated_updates: "Automated updates for KSA residency and labor guidance.",
    full_labor_gazette: "Full Labor Gazette",
    jobs_title: "Jobs in Saudi Arabia",
    jobs_subtitle: "Expat Career Portal",
    jobs_desc: "Find the latest jobs in Saudi Arabia for expats and explore career opportunities in Riyadh, Jeddah, and across the Kingdom.",
    jobs_local_network: "Local Network",
    jobs_local_network_desc: "We share profiles with trusted colleagues and companies whenever relevant job demands arise.",
    jobs_active_referral: "Active Referral",
    jobs_active_referral_desc: "We continuously try to match your skills and experience with current market requirements.",
    jobs_verified_partners: "Verified Partners",
    jobs_verified_partners_desc: "Your information is shared only with verified and professional recruitment-related entities.",
    jobs_technical_note: "Technical Note",
    jobs_technical_note_desc: "Applications submitted here are processed for internal review only. For official portal support, visit job.linux-aios.com.",
    jobs_official_portal: "Official Application Portal",
    jobs_official_portal_desc: "Access our main recruitment platform to browse all open positions, track your applications, and manage your profile.",
    jobs_open_portal: "Open Official Portal",
    jobs_alt_method: "Alternative Application Method",
    jobs_alt_method_desc: "If you are having trouble with the main portal, you can submit your application directly via our verified Form.",
    jobs_apply_form: "Apply via Form",
    jobs_secure_dropbox: "Secure CV Drop-box",
    jobs_secure_dropbox_desc: "Use our private submission system to upload your CV directly to our recruitment team. Your files are protected.",
    jobs_secure_upload: "Secure Upload to Drive",
    about_title: "About This Platform",
    about_subtitle: "Human-Centric Support",
    about_desc: "Empowering individuals in Saudi Arabia with simplified guides, labor rights awareness, and essential community resources.",
    about_main_p1: "This platform is created with the intention of supporting individuals living and working in Saudi Arabia by providing simplified guides, informational content, and awareness-based resources related to work, visas, labor rights, education, and daily life systems in the Kingdom.",
    about_goal_title: "Our Goal",
    about_goal_desc: "Our goal is to contribute positively to society by making complex government procedures easier to understand in a structured and user-friendly way.",
    about_vision_title: "Community Vision",
    about_vision_desc: "This platform is built with the intention of supporting the vision of a more informed and aware community in line with national development goals.",
    about_main_p2: "We aim to help people better understand official systems and procedures so they can make informed decisions in their daily life. Our intention is purely support-based and educational.",
    about_disclaimer_title: "Important Disclaimer",
    about_disclaimer_1_title: "1. Information Purpose Only",
    about_disclaimer_1_desc: "All content is for general informational purposes only. It is not legal or financial advice. Always verify via official sources.",
    about_disclaimer_2_title: "2. No Legal Responsibility",
    about_disclaimer_2_desc: "We are not a legal advisor or government authority. We are not responsible for any loss arising from reliance on this information.",
    about_disclaimer_3_title: "3. Official Verification Required",
    about_disclaimer_3_desc: "Verify all data from MHRSD, Absher, Qiwa, and other official portals. Official sources are final.",
    about_disclaimer_4_title: "4. No Payments or Fees Policy",
    about_disclaimer_4_desc: "This website is 100% free. We never ask for payments or donations. Report any fraudulent requests.",
    about_final_note_title: "Final Note to Users",
    about_final_note_desc: "Do not rely only on this website for final decisions. Always verify from official sources. Use this as a support guide, not a final authority.",
    about_founder_title: "Founder's Vision",
    about_founder_desc1: "The founder’s vision is to create a simple and reliable knowledge platform that helps people understand key systems in Saudi Arabia.",
    about_founder_desc2: "By leveraging community insights and official regulations, we aim to bridge the information gap and foster a more aware and empowered workforce within the Kingdom.",
    about_support_title: "Help & Support",
    about_support_desc: "If you have questions, need clarification on a guide, or want to report an issue, our team is here to help. Contact us via the support form or email for dedicated assistance.",
    about_terms_btn: "Terms & Conditions",
    resources_title: "Resources & Applications",
    resources_subtitle: "Digital Ecosystem",
    resources_desc: "The ultimate directory for official Saudi government platforms, essential mobile applications, and emergency contacts.",
    resources_security_title: "Critical Security Warning",
    resources_security_desc: "Only download government apps from the official Apple App Store or Google Play Store. Never share your OTP codes.",
    resources_emergency_title: "Emergency & Support Hotlines",
    resources_category_residency: "Identity, Residency & NIC",
    resources_category_finance: "Banking & Finance (SAMA)",
    resources_category_labor: "Labor, HRDF & GOSI",
    resources_category_traffic: "Traffic, Muroor & NAJM",
    resources_category_health: "Health & Insurance (CCHI)",
    resources_category_housing: "Housing & Finance (REDF)",
    resources_category_telecom: "Telecom, Taxes & ZATCA",
    resources_category_hajj: "Hajj & Umrah",
    calc_title: "End of Service",
    calc_subtitle: "Benefit Calculator",
    calc_desc: "Calculate your End of Service Benefit (Gratuity) based on the latest Saudi Labor Law regulations.",
    calc_basis_title: "Calculation Basis",
    calc_basis_desc: "First 5 Years: 1/2 month salary for each year. After 5 Years: 1 month salary for each year.",
    calc_legal_title: "Legal Authority",
    calc_legal_desc: "Calculations are based strictly on Article 84 and 85 of the Saudi Labor Law.",
    calc_salary_label: "Basic Salary (SAR)",
    calc_years_label: "Years",
    calc_months_label: "Months",
    calc_reason_label: "Reason for Leaving",
    calc_btn: "Calculate Benefit",
    calc_result_label: "Total Estimated Benefit",
    calc_note: "* This is an estimate based on Articles 84/85. Final settlements may include pending leave balances.",
    labor_title: "Maktab Amal",
    labor_subtitle: "Complete Guide for KSA Expats",
    labor_desc: "Maktab Amal (Labor Office) operates under MHRSD, serving over 11.5 million expatriate workers.",
    labor_intro_title: "What is Maktab Amal?",
    labor_intro_desc: "It is the government body responsible for regulating employer-employee relationships and processing work permits.",
    labor_feature_1: "Work Permit Processing",
    labor_feature_2: "Labor Dispute Resolution",
    labor_feature_3: "Nitaqat Management",
    labor_feature_4: "Wage Protection Oversight",
    labor_services_title: "Services Offered",
    labor_services_desc: "Maktab Amal manages the full lifecycle of employment in Saudi Arabia.",
    labor_cat_work: "Work Permits",
    labor_cat_contract: "Employment Contracts",
    labor_cat_wage: "Wage Protection",
    labor_cat_dispute: "Dispute Resolution",
    labor_cat_mobility: "Job Mobility",
    labor_cat_compliance: "Compliance",
    labor_location_title: "Locations & Hours",
    labor_location_subtitle: "Primary branches across the Kingdom.",
    labor_faq_title: "Frequently Asked Questions",
    home_hub_title: "Saudi Labor Authority Hub",
    home_hub_desc: "Explore our comprehensive SEO silos for detailed guidance on Saudi Arabia labor law, residency rules, and financial settlements.",
    home_silo_work_title: "Work & Visa System",
    home_silo_work_desc: "Work permits, Iqama renewals, and exit/re-entry visa processing.",
    home_silo_salary_title: "Salary & Payments",
    home_silo_salary_desc: "Download salary certificates and calculate GOSI insurance in KSA.",
    home_silo_eosb_title: "End of Service",
    home_silo_eosb_desc: "Calculate your EOSB, resignation settlements, and final dues.",
    home_silo_rights_title: "Labor Rights & Complaints",
    home_silo_rights_desc: "File salary delay complaints and know your legal worker rights.",
    home_silo_sponsor_title: "Sponsor Transfer System",
    home_silo_sponsor_desc: "Qiwa transfer status check and Naqal Kafala regulations.",
    home_silo_identity_title: "Identity & Residency",
    home_silo_identity_desc: "National Address registration and Absher identity services.",
    home_silo_edu_title: "Student & Education Hub",
    home_silo_edu_desc: "Schooling for expat children, GPA calculators, and writing utilities.",
    home_open_library_btn: "Open Complete Guide Library",
    footer_contacts: "Official Contacts",
    footer_moderated: "Moderated by verified community experts",
    footer_emergency: "Emergency Support: 19911 (MHRSD)",
    footer_serving: "Serving all of Saudi Arabia",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_rights: "All rights reserved.",
    hero_welcome: "Welcome! I'm your Saudi Labor Law Assistant. I'm here to provide you with verified information and guidance on MHRSD regulations, visas, and general expat affairs. How can I help you today?",
    hero_follow_up: "Ask a follow-up question...",
    hero_send: "Send",
    hero_consulting: "Consulting legal database...",
    hero_offline: "The AI Chat is currently offline because the GROQ_API_KEY is not configured in the system environment.",
    hero_network_error: "Network error. Unable to reach the AI engine.",
    hero_badge: "Official Community Portal",
    floating_support: "Email Support",
    hotline_emergency: "General Emergency",
    hotline_ambulance: "Ambulance / Red Crescent",
    hotline_labor: "Labor Support (MHRSD)",
    hotline_hajj: "Hajj & Umrah Support",
    res_app_available: "App Available",
    res_access_portal: "Access Portal",
    res_official_stores: "Official Stores Only",
    res_never_share_otp: "Never Share OTPs",
    nav_community: "Community",
    community_title: "Community Discussions",
    community_subtitle: "Connect & Share",
    community_desc: "Join the conversation with fellow expatriates in Saudi Arabia. Discuss labor laws, share your experiences, and help others.",
    community_login_required: "Please Sign in with Google to post or reply.",
    community_post_placeholder: "What's on your mind? Share an update or ask a question...",
    community_reply: "Reply",
    community_share: "Share",
    community_join_btn: "Join Discussion",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: () => {}, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
